Repository Azure/jumpstart-sdk, pull requests merged in 2025-05, with the labels that each got.

#324 Spell
  .github/spelling/config/vocabularies/Jumpstart/accept.txt
  .github/spelling/config/vocabularies/Jumpstart/reject.txt
  .github/spelling/spelling.txt
  .github/workflows/spelling.yml
  cspell_old/cspell-ignore-words.txt
  cspell_old/cspell.json
  cspell_old/reviewdog.yml
  cspell_old/spell-check.yml
  cspell_old/test_linting.md
Labels: Resolution-Duplicate

#330 LocalBox workflow
  .github/workflows/ps-module_azure.arc.jumpstart.localbox.yaml
Labels: LocalBox

#339 Add function to manage deployment progress tags
  powershell/modules/Azure.Arc.Jumpstart.Common/source/Azure.Arc.Jumpstart.Common.psd1
  powershell/modules/Azure.Arc.Jumpstart.Common/source/Public/Update-AzDeploymentProgressTag.ps1
Labels: ArcBox, LocalBox
